### PR TITLE
fix: return MCP-compatible responses for tool execution failures

### LINKED ISSUE #158: MCP Tool Execution Errors Use Wrong Format
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### AI Policy

- [x] I agree to follow this project's AI Policy, or I agree that AI was not used while creating this issue.

## Environment

- **Elixir:** 1.19.0
- **Erlang/OTP:** 28
- **ash_ai:** 0.4.0 (latest on hex as of 2025-11-23)
- **ash:** 3.11.3
- **ash_json_api:** 1.5.1

## Verified in Latest Version

I confirmed the issue exists in ash_ai 0.4.0 (latest). The CHANGELOG shows no fixes for MCP error serialization in 0.3.0 or 0.4.0. The `Jason.encode!()` call is still present in the current `main` branch source code.

### Operating system

Ubuntu

### Current Behavior

MCP tool execution errors are returned as JSON-RPC errors instead of MCP-compliant `isError: true` responses. This causes clients to receive generic "Tool execution failed" messages instead of actionable error details.

When a tool execution fails (e.g., validation error), the MCP server returns:

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32000,
    "message": "Tool execution failed",
    "data": {
      "errors": [...]
    }
  }
}
```

**Result for LLM/Client:** `MCP error -32000: Tool execution failed` - no useful error details.

### Reproduction

1. Set up an MCP server with any Ash resource
2. Call a tool action with invalid input (e.g., missing required fields)
3. Observe the error response has `data.error` as a JSON string instead of a structured array

### Expected Behavior

According to the [MCP specification (2025-06-18)](https://modelcontextprotocol.io/specification/2025-06-18/server/tools):

> If the tool execution fails, servers SHOULD set `isError` to true and include error details in the content. Error handling should be done within tool results rather than at the protocol level.

Tool execution errors should return a **successful response** with `isError: true`:

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "isError": true,
    "content": [
      {
        "type": "text",
        "text": "/data/relationships/personas: At least one persona is required"
      }
    ]
  }
}
```

**Result for LLM/Client:** `/data/relationships/personas: At least one persona is required` - actionable error message.

## Proposed Fix

The issue has two parts:

### 1. Wrong Error Format in `server.ex`

In `lib/ash_ai/mcp/server.ex`, the `handle_json_rpc_request` function returns tool execution errors as JSON-RPC errors:

```elixir
# Current (incorrect)
{:error, errors} ->
  response = %{
    "jsonrpc" => "2.0",
    "id" => id,
    "error" => %{
      "code" => -32_000,
      "message" => "Tool execution failed",
      "data" => %{"errors" => errors}
    }
  }
```

### 2. Double-Serialization in `tools.ex`

In `lib/ash_ai/tools.ex`, the `run_mcp_resource_action/3` function JSON-encodes the error before returning:

```elixir
# Current (incorrect)
{:error, error} ->
  error = Ash.Error.to_error_class(error)

  {:error,
   domain
   |> AshJsonApi.Error.to_json_api_errors(resource, error, action.type)
   |> AshAi.Serializer.serialize_errors()
   |> Jason.encode!()}  # <-- This causes double-serialization
```

### 1. Change Error Format to MCP-Compliant `isError: true`

In `lib/ash_ai/mcp/server.ex`, replace the JSON-RPC error with a successful response containing `isError: true`:

```elixir
{:error, errors} ->
  # Per MCP specification (2025-06-18), tool execution errors should be
  # returned as successful responses with isError: true, NOT as JSON-RPC errors.
  # This allows LLMs to see and handle the error appropriately.
  # See: https://modelcontextprotocol.io/specification/2025-06-18/server/tools
  error_text = format_tool_errors(errors)

  result = %{
    "isError" => true,
    "content" => [%{"type" => "text", "text" => error_text}]
  }

  response = %{
    "jsonrpc" => "2.0",
    "id" => id,
    "result" => result
  }

  {:json_response, Jason.encode!(response), session_id}
```

### 2. Add Error Formatting Helpers

Add helper functions to format errors into readable text:

```elixir
@doc """
Format tool execution errors into a human-readable text message.
"""
def format_tool_errors(errors) when is_list(errors) do
  formatted =
    errors
    |> Enum.map(&format_single_error/1)
    |> Enum.reject(&is_nil/1)
    |> Enum.join("\n")

  if formatted == "" do
    "Tool execution failed"
  else
    formatted
  end
end

def format_tool_errors(_), do: "Tool execution failed"

defp format_single_error(%{} = error) do
  field =
    case error do
      %{source: %{pointer: pointer}} when is_binary(pointer) -> pointer
      %{source: %{parameter: param}} when is_binary(param) -> param
      %{"source" => %{"pointer" => pointer}} when is_binary(pointer) -> pointer
      %{"source" => %{"parameter" => param}} when is_binary(param) -> param
      _ -> nil
    end

  detail =
    case error do
      %{detail: detail} when is_binary(detail) -> detail
      %{"detail" => detail} when is_binary(detail) -> detail
      %{title: title} when is_binary(title) -> title
      %{"title" => title} when is_binary(title) -> title
      %{message: message} when is_binary(message) -> message
      %{"message" => message} when is_binary(message) -> message
      _ -> nil
    end

  cond do
    field && detail -> "#{field}: #{detail}"
    detail -> detail
    field -> "Error at #{field}"
    true -> nil
  end
end

defp format_single_error(_), do: nil
```

### 3. Remove Double-Serialization in `tools.ex`

In `lib/ash_ai/tools.ex`, remove the `Jason.encode!()` call:

```elixir
{:error, error} ->
  error = Ash.Error.to_error_class(error)

  # Return structured errors, not JSON-encoded string
  # The MCP server will handle formatting via format_tool_errors/1
  {:error,
   domain
   |> AshJsonApi.Error.to_json_api_errors(resource, error, action.type)
   |> AshAi.Serializer.serialize_errors()}
```

### Why JSON-RPC Errors Are Wrong for Tool Execution

The MCP specification distinguishes between two types of errors:

| Error Type | When to Use | Format |
|------------|-------------|--------|
| **Protocol Errors** | Invalid requests, unknown methods, transport failures | JSON-RPC `error` object |
| **Tool Execution Errors** | Validation failures, business logic errors, resource not found | `isError: true` in result |

Using JSON-RPC errors for tool execution:
- Hides error details from LLMs (they only see "Tool execution failed")
- Prevents LLMs from self-correcting based on error messages
- Breaks the MCP contract that tools should handle their own errors

### Test Results

**Before fix:**
```
MCP error -32000: Tool execution failed
```

**After fix:**
```
/data/relationships/personas: At least one persona is required
```

### References

- [MCP Specification - Tools](https://modelcontextprotocol.io/specification/2025-06-18/server/tools)
- [MCP Error Handling Best Practices](https://www.mcpevals.io/blog/mcp-error-codes)

### Implementation

A working implementation is available at:
- Repository: https://github.com/catalioapp/ash_ai
- Branch: `fix/mcp-error-serialization`

## Environment

- ash_ai version: 0.3.x (from hex)
- Tested with MCP Inspector and curl

### PR DESCRIPTION
**Pull request by sukidhar**
Closes #158 

Hi, I went through the long instructions mentioned in the issue and tried to find references of `to_json_api_errors`, which is used to format tool execution failures in `Errors.format`, and found that it is only being used once, and that's at the tool execution failure point alone. I tried to keep it simple and used the existing `Exception` module to fetch the message as an error string and join them. The response is later constructed in `server.ex`, where the response format follows directly from the [mcp docs](https://modelcontextprotocol.io/specification/2025-06-18/server/tools#error-handling). I also checked that it is compatible with latest version dated 2025-11-25. I have removed a significant chunk of code that is no longer in use as per the other changes. I ran the check command and found that one test is failing. I admit that I used a little bit of Claude's help to generate new tests; previously the `Errors` module did not have any tests, so I added them to ensure it works.

Happy to adjust this PR and learn more about Ash, if at all I understood the code wrongly. 

# Contributor checklist

Leave anything that you believe does not apply unchecked.

- [x] I accept the [AI Policy](https://github.com/ash-project/.github/blob/main/AI_POLICY.md), or AI was not used in the creation of this PR.
- [x] Bug fixes include regression tests
- [ ] Chores
- [ ] Documentation changes
- [ ] Features include unit/acceptance tests
- [x] Refactoring
- [ ] Update dependencies

### CODE REVIEW

File: lib/ash_ai/tool/errors.ex [hunk 1]
```diff
@@ -4,58 +4,32 @@
...
-      |> add_if_defined(:status, to_string(error.status_code))
-      |> add_if_defined(:code, error.code)
-      |> add_if_defined(:title, error.title)
-      |> add_if_defined(:detail, error.detail)
-      |> add_if_defined([:source, :pointer], error.source_pointer)
-      |> add_if_defined([:source, :parameter], error.source_parameter)
-      |> add_if_defined(:meta, parse_error_meta(error.meta))
+    |> Map.get(:errors, [])
+    |> Enum.map_join("\n", fn error ->
+      msg = Exception.message(%{error | bread_crumbs: []})
```
Comment (zachdaniel) [inline lib/ash_ai/tool/errors.ex]: We unfortunately cannot use `Exception.message`. This displays internal information. We need to have an explicit protocol similar to what AshJsonApi and AshGraphql has. We can implement the default protocols in the same way that AshJsonApi does for example, and should log when we don't get a protocol implementation.

Comment (sukidhar) [reply lib/ash_ai/tool/errors.ex]: Okay, I will check the implementations and rework that piece

Comment (sukidhar) [reply lib/ash_ai/tool/errors.ex]: I have updated the PR as per your guidance, kept the changes and minimal and this also gave me clean opportunity to introduce tests  for various impls.

File: lib/ash_ai/tool/errors.ex [hunk 2]
```diff
@@ -4,58 +4,43 @@
...
+    msg =
+      if AshAi.ToToolError.impl_for(error) do
+        AshAi.ToToolError.to_tool_error(error)
+      else
+        Logger.warning("AshAi.ToToolError not implemented for #{inspect(error.__struct__)}")
+
+        "unexpected error occurred"
+      end
+
+    if field = Map.get(error, :field) do
```
Comment (zachdaniel) [inline lib/ash_ai/tool/errors.ex]: Looking good! Only thing that we need to do now is handle the case where there are multiple `fields`, as well as when there is a path. It would look something like this:

- if error.fields is present, then iterate over each field and call this function again with `%{error | fields: nil, field: that_field}`
- if error.path is present, then field becomes `Enum.join(error.path ++ [error.field])`

Comment (sukidhar) [reply lib/ash_ai/tool/errors.ex]: Okay will make this change shortly and update here

Comment (sukidhar) [reply lib/ash_ai/tool/errors.ex]: I have updated this code as you instructed. I added some more tests to cover this cases

**Review by zachdaniel — APPROVED** [review]
